#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${DIR}"

source ./functions.config.sh

if [ -z "${FIRESTORE_COLLECTION}" ]; then
    echo "FIRESTORE_COLLECTION env is not set"
    exit 1
fi

if [ -z "${API_SECRET_KEYS}" ]; then
    echo "API_SECRET_KEYS env is not set"
    exit 1
fi


GO_CONFIG_FILE="${DIR}/GetAutogeneratedConfig.go"

cat >"${GO_CONFIG_FILE}" <<EOF
package function

import "github.com/Jblew/inspector-widget-osowiec/functions/app"

// GetAutogeneratedConfig is automatically generated file with device config
func GetAutogeneratedConfig() app.Config {
	var conf = app.Config{}
	conf.FirestoreCollection = "${FIRESTORE_COLLECTION}"
    conf.SecretKeys = "${API_SECRET_KEYS}"

	return conf
}

EOF
